project:
  type: book
  output-dir: docs
  
book:
  title: "Trajectories of local development and public opinion"
  subtitle: "Environmental policy in Umbria"
  author:
    - name: "Lorenzo Mattioli"
      affiliations:
    - name: "Alma Mater Studiorum - Università di Bologna"
      department: "SPS - Scienze Politiche e Sociali"
      
  keyword: 'social stratification'
  date: "2/24/2025"
  # cover-image: cover.png
  search: true
  downloads: [pdf, epub]
  repo-url: 'https://github.com/stars/lorMatt/lists/lm-and-public-opinion-in-umbria'
  navbar:
    left:
      - text: My blog
        href: https://lormatt.github.io/

      
  chapters:
    - index.qmd
    - intro.qmd
    - review_framework.qmd
    - umbria.qmd
    - data_methods.qmd
    - results_discussion.qmd
    - conclusions.qmd
    - references.qmd
  appendices:
    - Pre-processing.qmd
    - Text retrieval.qmd

bibliography: references.bib

format:
  html:
    theme: simplex
    lightbox: true
    number-sections: false
    # number-depth: 3
    toc: true

editor: visual

