project:
  type: book
  output-dir: docs
  
book:
  title: "Trajectories of local development and public opinion"
  subtitle: "Environmental policy in Umbria"
  author:
    - name: 'Lorenzo Mattioli'
      email: lorenzomattioli@protonmail.com
    - name: 'Marco Albertini (supervisor)'
      orcid: 0000-0003-0344-3002
    - name: 'Arianna Tassinari (co-supervisor)'
      orcid: 0000-0001-5437-935X
  date: "07/18/2025"
  search: true
  
  navbar:
    left:
      - text: Blog
        href: https://lormatt.github.io/
    right:
      - icon: github
        href: https://github.com/stars/lorMatt/lists/lm-and-public-opinion-in-umbria
      # - icon: envelope
      #   href: mailto::lorenzomattioli@protonmail.com
      - icon: download
        menu:
          - text: "<i class='bi bi-file-earmark-pdf'></i> Download PDF"
            href: Trajectories-of-local-development-and-public-opinion.pdf
          - text: "<i class='bi bi-book'></i> Download EPUB"
            href: Trajectories-of-local-development-and-public-opinion.epub
  chapters:
    - index.qmd
    - intro.qmd
    - review_framework.qmd
    - umbria.qmd
    - data_methods.qmd
    - results_discussion.qmd
    - conclusions.qmd
    - references.qmd
  appendices:
    - Pre-processing.qmd
    - Text retrieval.qmd


      

bibliography: references.bib

format:
  html:
    theme: simplex
    lightbox: true
    number-sections: false
    toc: true

editor: visual

