project:
  type: book
  output-dir: docs
  
book:
  title: "Trajectories of local development and public opinion"
  subtitle: "Environmental policy in Umbria"
  author:
    - name: "Lorenzo Mattioli"
    - name: 'Marco Albertini (supervisor)'
    - name: 'Arianna Tassinari (co-supervisor)'
  date: "7/18/2025"
  search: true
  navbar:
    left:
      - text: My blog
        href: https://lormatt.github.io/
      - icon: github
        href: https://github.com/stars/lorMatt/lists/lm-and-public-opinion-in-umbria
      - icon: download
        menu: 
          - text: "<i class='bi bi-file-earmark-pdf'></i> Download PDF"
            href: Trajectories-of-local-development-and-public-opinion.pdf
          - text: "<i class='bi bi-book'></i> Download EPUB"
            href: Trajectories-of-local-development-and-public-opinion.epub
  chapters:
    - index.qmd
    - intro.qmd
    - review_framework.qmd
    - umbria.qmd
    - data_methods.qmd
    - results_discussion.qmd
    - conclusions.qmd
    - references.qmd
  appendices:
    - Pre-processing.qmd
    - Text retrieval.qmd


      

bibliography: references.bib

format:
  html:
    theme: simplex
    lightbox: true
    number-sections: false
    toc: true

editor: visual

