# Introduction

The last decades have witnessed the rise of an interrelation in the public debate between industrial and environmental policies. In layman terms, the discussion has often revolved around two opposite arguments: a supposed trade-off between environmental policy and economic development, thus including job security [@vona2019]. This may seem unreasonable to an academic audience for two reasons. First and foremost, there are fairly strong theoretical grounds to the claim that an energy transition would lead to an increase in labour demand at the aggregate level [@smith2007]. This fact alone would make framing the problem as a zero-sum game irrational in the eyes of an economist. Second, to the average natural scientist, balancing concerns on occupation with the perspective of mass extinction might seem silly at best. To the workers employed in those industries which face the threat of extinction, however, the choice between job security and mitigating climate change is all but obvious. The key to explaining support for environmental policy could be found in the fear of experiencing a feeling of *loss* and noxious deindustrialisation [@feltrin2022; @jackson2018]. This project therefore insists on the importance of analysing labour markets to explain public opinion formation around the issue of climate and environmental policy. In particular, the project aims to answer the following research question:

> Is public discourse on environmental policy correlated to a local economy's *exposure* to the energy transition?

In order to start explaining this phenomenon, however, one first has to *establish* it. The present study will hence delineate the theoretical premise such question is based on, but refrain from advancing any causal claims. Using the Umbria region (central Italy) as a case study, an empirical exploration of the phenomenon will be conducted. Such endeavour will be carried out through computational methods, by analysing a sample of online press releases and videos. The content of the subsequent chapters is summarised below:

In the second chapter, the importance of adopting a localised perspective will be stated and discussed. The concept of *loss* will be defined and adapted to the specific case of environmental policy. The theoretical lens through which the present analysis of public discourse is conducted will be spelled out, before briefly discussing the arguments behind case selection.

In the third chapter, the two selected cases will be described and compared from a historical point of view, in order to provide the necessary context for the subsequent analysis.

In the fourth chapter, the sample selection strategy will be presented. The two resulting corpora will be then described in detail before defining the analytical strategy adopted to produce the results enumerated in chapter five.

The results will be finally discussed in the sixth chapter, in which the limitations of the present study will be also assessed, and the key findings summarised in a brief concluding section.
