# Environmental policy and public discourse

## The importance of a local perspective

Climate change is a complex, multifaceted phenomenon. Its consequences manifest in different ways across territories and regions, and are borne unequally by different groups [@calvin2023]. In the most pragmatic sense, some areas may be prone to flooding, while others are subject to desertification. Through a breakdown of the impacts of climate change at regional level, @rodríguez-pose2023 found that European cities are less vulnerable than rural areas. There is thus a consolidated consensus both in the natural sciences and in literature on the energy transition that climate change should be understood as a *localised* phenomenon, where each political community faces different problems and tailors its solutions to pre-existent socio-economic and environmental conditions [@pörtner2023; @smith2007]. The latter should be considered path-dependent, as in informed and constructed by the history of a certain region. It follows that the social scientist's approach on this topic should not fundamentally differ from that of a natural scientist. Just like the biologist takes the ecological context into account when analysing the health of a natural habitat, a sociologist or political scientist cannot forget to consider local idiosyncrasies when analysing the socio-economic conditions of an artificial one [@dunlap2015]. This becomes especially apparent in areas whose economic activity is more clearly linked to its climate: Hamilton and colleagues, for instance, found that areas which used to thrive off of skiing suffer more acutely from the adverse economic effects of the climate crisis as compared to other, less vulnerable areas [@hamilton2003]. A similar argument can be made for socio-economic vulnerability to environmental policy. A regional economic system which is based on inherently polluting activities will have to undergo more fundamental change than one whose economy is centred around *green-er* ones. In a context where goals and strategies are set at a higher-than-regional level, environmental policy might find some regions more *ready* than others. To differentiate it from *vulnerability* to the natural consequences of climate change, this concept will be hereinafter referred to as a local economy's *exposure* to environmental policy.

The political outlook on climate change also appears to be geographically informed. In the most down-to-earth fashion, the occurrence of climate anomalies and rising temperature trends in a particular area have been proven to be reliable predictors of individuals' outlook on climate change as an artificial phenomenon [@hamilton2009; @hamilton2013]. This makes the case for adopting a local perspective even more compelling in a study concerned with public discourse.

## De-industrialisation and patterns of *loss*

As discussed above, the overwhelming presence of job-loss arguments in the public discussion on environmental policy is hardly explainable with the traditional tools of economic *rationality*, since its effects should benefit the whole population indiscriminately both in terms of occupation and health. In *exposed* regional economies, however, workers of *brown*, polluting jobs might have a harder time dismissing the notion of environmental policy as a *zero-sum* game, where an improvement in public health is balanced out by a decline in employment and job security.

In a post-industrial context, workers in exposed economies often experience *noxious* de-industrialisation. *Noxiousness* is a translation from the Italian *Nocività*, a word used by the Italian labour movement in the sixties to identify *production-induced damage against both human and non-human life* [@feltrin2021]. By noxious de-industrialisation, @feltrin2022 identify a scenario in which job loss and toxic pollution coexist, where the old factories are still operative (and polluting), but employ a fraction of the original workforce. To the inhabitants of an area which used to thrive off of industrial activity, the post-industrial experience is one of loss and decline. As @jackson2018 poignantly point out, *concentrated* loss, as in loss attributable to a single group, can lead to its *politicisation*. What this means is that those active or employed in *exposed* economies might interpret environmental policy as a covertly distributional zero-sum game, where blue collar industrial workers lose out to urban, service-class elites, active in *green*, future-proof sectors of the economy. The truthfulness of the (re-) distributional claim is of little interest in this instance, although a fear of loss in exposed economies does not appear to be groundless: in Europe, the intensity of toxic pollution is still positively associated with employment and wages at the industrial level (and specifically in the energy sector), while a reduction of pollutants at facility level is associated to lower employment and wages [@bez2022]. Following @jackson2018 and their *Post-liberal theory of social stratification*, resentment, resistance, and retrenchment against environmental policy should be then expected from those who feel that their jobs are endangered by it.

## Theoretical framework and research questions

As discussed above, in exposed economies, we expect the dominant narrative around environmental policy to be one of a zero-sum game [@jackson2018]. The aim of this study, however, is to *establish* rather than explain the phenomenon at hand. The approach adopted is therefore clearly a grounded, descriptive one.

The central research question is thus the following:

> *Can the characteristics of public discourse around environmental policy be correlated to a regional economy's* exposure *to environmental policy?*

### Public discourse analysis

In order to detect shifts in public discourse, we turn to media. This is a somewhat unorthodox approach: in stark contrast with the more consolidated practice of considering media to have an active role in shaping narratives and political concepts, they will be here thought of as responsive to public opinion *on the ground*. This is a rather common concept in social movements research, where issue salience and awareness are thought to be influenced by mobilisation [see, for instance: @carey2014]. Classic concepts in agenda-setting theory, however, still represent this study's theoretical core. Environmental policy will be here analysed in terms of its *salience* in local media [@mccombs1976]. Heavy media emphasis on environmental policy (salience) will be treated as a sign of it ranking higher in personal agendas in a certain area. Its *attributes*, as in its sub-issues and relationship with other policy areas, will be here aptly qualified.

### Economic *exposure*

The concept of economic *exposure* (as in vulnerability to the energy transition) is here operationalised through the identification of two localised labour market conditions:

-   Having previously experienced industrial decline and suffered the consequences of noxious deindustrialisation;

-   Presenting a prevalence of brown jobs.

The hypothesised mechanism underpinning the relationship between economic exposure and zero-sum discourse can be summarised as follows: living in an area experiencing industrial decline means being exposed to a narrative in which members of previous generations remember times when they could sustain a comparatively higher standard of living. When combined with the lack of immediate economic alternatives compatible with the green transition, this feeling could develop into a structured belief in the fact that progress towards a greener future does not, in fact, benefit anyone else other than those who already have better life chances, thus producing ubiquitous *loss*. Such fear of future downward mobility would then manifest itself in public discourse.

### Methodological pursuit

This study's goal is to advance knowledge on the topic by integrating standard quantitative approaches with those of computational social science. Using the web as a data source, online news outlets and YouTube videos will be analysed through natural language processing methods borrowed from computational linguistics. Through the application and comparison of different analytical strategies, this study will offer a complete overview of the phenomenon.

## Case selection

The strategy of choice is that of a comparative case study. For this investigation's purpose, the ideal cases would be two areas comparable in terms of their cultural and political background, but displaying variation in terms of the labour market conditions above. The Umbria region in central Italy thus represent a good candidate. Its two main cities (Perugia and Terni) have a similar stock of residents, respectively 162099 and 106436 in 2024, and share a common cultural and political background, their polities having been intertwined at least since 1970, when they were chosen as the two provincial capitals of the newborn Umbria region [@istat]. Their economic and social history, however, is deeply different.
