# The case of Umbria

## Umbria as a case study

Terni has a long industrial history, its identity revolving around its steel factory. After decades of decline and job loss, the factory now employs a fraction of the people it did in the 1980s, while still exerting a very negative impact on the city's air quality. Terni is a textbook case of noxious de-industrialisation, the extensive employment losses becoming even more painful as they are the proof of multiple labour failures over decades [@portelli; @portelli2017]. Perugia, on the other hand, thrives off of its long academic tradition, its economic activity being mostly centred around the service economy, hospitality and confectionery. De-industrialisation is mostly unknown to the population of a city that was simply never truly industrialised. Its expansion over the last twenty years made transportation become the main topic of political debate.

Perugia and Terni clearly display very different characteristics in terms of the labour market conditions: the experience of industrial decline of noxious deindustrialisation so familiar to Terni's population is completely alien to Perugia's, where heavy industry plays an almost quantitatively irrelevant role in the local economy. Nonetheless, their polities and politics have been closely intertwined for at least half a century, due to the fact that they are the only two provincial capitals of the Umbria region. These factors make them perfect to conduct a comparative case study on.

## Terni's industrial history

Up to the 1880s, Terni was a medium-sized rural town of no particular interest other than the occasional visit from English painters and poets to the nearby waterfalls or the castles along the Nera valley. Although, as stressed by @vaqueropiñeiro2020, the area was historically no stranger to manufacture, the establishment of the *Società degli altoforni, fonderie e Acciaierie di Terni* ("Society of blast furnaces, foundries and steelworks of Terni") in 1884 was a defining moment in the city's history, turning it into a full-fledged industrial town. The steel factory underwent numerous name changes as it expanded, and was finally nationalised in the 1930s. With the steel came weapons, chemicals, electrical plants and pipe mills. The production, which initially comprised solely of stainless steel, came to include cutting-edge magnetic steel, engines, turbines, all while pulling the city toward higher incomes and better education, at the expense of air quality and intense urbanisation. Since then, Terni's identity evolved around heavy industry. Its urban design was catered to the needs of its industry, before and after being heavily bombed during WWII due to its strategic relevance. Workers' dwellings and guest quarters still crowd every area of the town. A bright-green, 12-ton steel press greets the occasional visitor right in front of the train station. In the city centre, a loud siren resounds every day at noon signalling the end of the morning shift at the factory.

In recent years, however, the town's industrial heritage started clashing with its present. After the steel factory's privatisation in 1994, the new German-led corporate ownership immediately exported patents to Germany and started progressively cutting down on personnel. A first *traumatic* event for the town was to witness Thyssen-Krupp's decision to move the highly coveted production of magnetic steel to Germany in 2004, non-withstanding the massive protests which flooded the city [@portelli]. In 2012, Finnish group Outokumpu tried acquiring the whole of Inoxum (Thyssen-Krupp's inox steel division), but was forced by the European Commission to give up Inoxum's assets in Italy, including *Acciai Speciali Terni* ("Terni Special Steel", which was then the factory's new name) [@bellomo2012; @meneghello2012]. After looking for a buyer for two years to no avail, Outokumpu gave AST back to Thyssen-Krupp, which then decided to downsize it in order to sell it more easily [@ternioggi2013]. To this end, Lucia Morselli (whose nickname was already *la tagliateste*, the axewoman) was appointed CEO, with the explicit mandate of dramatically cutting down on the workforce. This sparked an unprecedented struggle between the ownership and the workforce. The tension became unsustainable, with all-out strikes being called by every union, and Morselli being even detained in her own office a whole night by protesters [@ugolini2014; @umbriajournal2014]. The result of the 2014 struggle, however, was considered by many an utter and complete loss for unions and the workforce. Morselli offered the protesters "compensation" (equal to the unpaid salary for the time they spent on strike), which most workers accepted [@portelli].

The personnel of a steel factory that used to employ over 10000 people up to a few decades ago, now amounts a mere 2300 units [@ast:arv]. The industry's adverse effects on public health, however, did not falter one bit. We can consider Terni to be a textbook case of noxious deindustrialisation, as @feltrin2022 define it, since widespread job loss came with no reduction in toxic pollution. The historical presence of three waste incinerators (of which only one is currently operative) unsurprisingly contributes in fuelling a considerable amount of spontaneous public health and environmental activism [@toni2024; @ternitoday2020]. From the 2010s onwards, a wide range of local pressure groups emerged: one movement (*No Inceneritori*, "no incinerators") became especially popular and influential, while the high school students at the head of Terni's *Fridays for Future* branch assumed a prominent role in its national organisation. Although the COVID19 pandemic put a noticeable dent in the city's grassroots political activity, this moment of its recent history is still fresh in Terni's collective memory. The ubiquitous feeling of *loss* generated by the city's industrial decay in Terni's population, joined with its recent mobilisation around environmental policy, makes it a perfect case to be here analysed.

## Perugia as a comparison case

After centuries as part of the papal state, Perugia's economic history is essentially one of stagnation up until the 20th century. In 1922, Hotel Brufani was the starting point of the fascist March on Rome [@albanese2006]. This made Perugia suddenly become a symbol to the newborn regime, which financed significant embellishments to the city. Its industry, however, remained largely underdeveloped. The city's marginal strategic importance meant that it was mostly spared by Allied bombers during WWII.

The city of Perugia is also home to one of the Europe's oldest universities (*Università di Perugia*, founded in 1308), as well as to the University for Foreigners (*Università per Stranieri di Perugia*, UNISTRA) [@theeditorsofencyclopaediabritannica2020]. Perugia's rich cultural heritage was a decisive factor in 1970, when it was chosen to become capital of the newborn Umbria region.

Its economy nowadays is mostly based on the service economy, driven by festivals and large cultural events such as *Umbria Jazz* and the Journalism Festival. Although heavy industry does play a (quantitatively marginal) role in non-urban areas in the province of Perugia, manufacture-related economic activity in the city's immediate vicinity pertains mostly to the confectionery and textile sectors. Notable examples of the like are *Perugina*'s headquarters and *Nestlè*'s main Italian branch, as well as *Luisa Spagnoli*'s textile plant. A considerable amount of smaller mechanical and artisanal firms bloomed in the outskirts of the city, which expanded almost incontrollably during the last 20 years.
